version: '3.5'

services:
  cfc-server:
    image: github.blokaly/currencyfair-challenge-server
    container_name: cfc-server
    environment:
      - PROFILE_NAME=production
    network_mode: "host"
    restart: unless-stopped